server {
    listen 80 default_server;
    listen 443 default_server;

    server_name pronto;

    location /static/ {
        alias /srv/src/app/static/;
    }

    location /media/ {
        alias /srv/src/app/media/;
    }

    location / {
        proxy_set_header Host $host;
        proxy_pass http://python:8000;
    }
}