version: "3"

services:
  python:
    container_name: python_${PROJECT_NAME}
    build:
      context: ./
      dockerfile: docker/configs/python/Dockerfile
      args:
        WORKDIR: ${WORKDIR}
    ports:
      - "${LOCAL_PORT}:${WSGI_PORT}"
    volumes:
      - ./src:${WORKDIR}/src
      - ./commands:${WORKDIR}/commands
      - ./static:${WORKDIR}/static
      - ./media:${WORKDIR}/media
    env_file: .env
    command: ./commands/start_server_${MODE}.sh
    depends_on:
      - postgres

  nginx:
    container_name: nginx_${PROJECT_NAME}
    image: nginx:1.27
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/configs/nginx:/etc/nginx/conf.d
      - ./static:${WORKDIR}/static
      - ./media:${WORKDIR}/media
    env_file: .env
    depends_on:
      - python

  postgres:
    container_name: postgres_${PROJECT_NAME}
    image: postgres:16.4
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    container_name: redis_${PROJECT_NAME}
    image: redis:alpine3.18
    env_file: .env
    restart: on-failure
    depends_on:
      - python

#  redisadmin:
#    container_name: redisadmin_${PROJECT_NAME}
#    image: redislabs/redisinsight
#    ports:
#      - "${REDIS_ADMIN_PORT}:5540"
#    env_file: .env
#    restart: on-failure
#    depends_on:
#      - redis

  celery:
    container_name: celery_${PROJECT_NAME}
    build:
      context: ./
      dockerfile: docker/configs/python/Dockerfile
      args:
        WORKDIR: ${WORKDIR}
    volumes:
      - ./src:${WORKDIR}
      - ./commands:${WORKDIR}/commands
      - ./media:${WORKDIR}/media
    env_file: .env
    environment:
      CELERY_GENERATE_IMAGE: 1
    restart: on-failure
    command:
      - ./commands/start_celery.sh
    ports:
      - "${FLOWER_PORT}:5555"
    depends_on:
      - redis
      - python

#  celerybeat:
#    container_name: celerybeat_${PROJECT_NAME}
#    build:
#      context: ./
#      dockerfile: docker/configs/python/Dockerfile
#      args:
#        WORKDIR: ${WORKDIR}
#    volumes:
#      - ./src:${WORKDIR}
#      - ./commands:${WORKDIR}/commands
#    env_file: .env
#    restart: on-failure
#    command: ./commands/start_celerybeat.sh
#    depends_on:
#      - redis
#      - python

#  pgadmin:
#    container_name: pgadmin_${PROJECT_NAME}
#    image: dpage/pgadmin4
#    ports:
#      - "${PGADMIN_PORT}:80"
#    volumes:
#      - pg_admin:/var/lib/pgadmin
#    env_file:
#      - .env
#    depends_on:
#      - postgres
#    restart: on-failure
#
#  mongo:
#    container_name: mongodb_${PROJECT_NAME}
#    image: mongo:7-jammy
#    ports:
#      - "${MONGO_PORT}:27017"
#    volumes:
#      - mongo_data:/data/db
#    env_file:
#      - .env
#    restart: on-failure
#
#  mongo_express:
#    container_name: mongo_express_${PROJECT_NAME}
#    image: mongo-express:latest
#    ports:
#      - "${ME_PORT}:8081"
#    env_file:
#      - .env
#    depends_on:
#      - mongo
#    restart: on-failure


volumes:
  pg_data: {}
#  pg_admin: {}
#  mongo_data: {}
#  static_content: {}
#  media_content: {}