version: "3"

services:
  python:
    container_name: python_${PROJECT_NAME}
    build:
      context: ./
      dockerfile: docker/configs/python/Dockerfile
      args:
        WORKDIR: ${WORKDIR}
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ./:${WORKDIR}
    env_file: .env
    command: ./commands/start_server_${MODE}.sh
    depends_on:
      - postgres

  postgres:
    container_name: postgres_${PROJECT_NAME}
    image: postgres:16.4
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      WORKDIR: ${WORKDIR}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: {}