# Generated by Django 5.1.2 on 2024-11-25 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_category_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SliderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="title"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        max_length=15360,
                        upload_to="products",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=("png", "jpg", "jpeg", "gif", "webp")
                            )
                        ],
                        verbose_name="image",
                    ),
                ),
                (
                    "order_number",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="order number",
                    ),
                ),
            ],
            options={
                "ordering": ["order_number"],
            },
        ),
    ]
