# Generated by Django 5.1.2 on 2024-11-25 22:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_slideritem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slideritem",
            name="image",
            field=models.ImageField(
                max_length=15360,
                upload_to="sliders",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("png", "jpg", "jpeg", "gif", "webp")
                    )
                ],
                verbose_name="image",
            ),
        ),
    ]
