# Generated by Django 5.1.2 on 2024-11-25 23:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_alter_slideritem_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slideritem",
            name="order_number",
            field=models.PositiveSmallIntegerField(
                default=1,
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
                verbose_name="order number",
            ),
        ),
    ]
